name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-components:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [infrastructure, frontend]
        node: [12]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Test ${{ matrix.package }}
        run: |
          cd ${{ matrix.package }}
          npm install
          npm run test
